version: '3.3'
services:
  jenkins:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"  
    restart: always
    privileged: true
    volumes:
      - jenkins_home:/var/jenkins_home
      - /home/devuser/simple-java-maven-app:/home/devuser/simple-java-maven-app  
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS="-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true"
volumes:
  jenkins_home:
          external: true
